[Manifest]
Version = 1

[Package]
Namespace = "Rux"
Name = "Io"
Version = "0.1.0"
Type = "Source"
Description = "Streams, console I/O, readers, and writers"
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies]
Bsd = { Namespace = "Rux", Version = "*" }
Format = { Namespace = "Rux", Version = "*" }
Linux = { Namespace = "Rux", Version = "*" }
MacOS = { Namespace = "Rux", Version = "*" }
Memory = { Namespace = "Rux", Version = "*" }
Rux = { Namespace = "Rux", Version = "*" }
Text = { Namespace = "Rux", Version = "*" }
Windows = { Namespace = "Rux", Version = "*" }
