[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Namespace = "Rux"
Name = "Format"
Version = "0.1.0"
Type = "SourceLibrary"
Description = "String conversion and formatting"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
Keywords = ["Format", "Formatting", "Conversion", "Strings", "Parsing"]
License = "MIT"
LicenseFile = "LICENSE.md"
Repository = "https://github.com/rux-lang/Rux"
Homepage = "https://rux-lang.dev/docs/api/format"
ReadmeFile = "README.md"

[Dependencies]
Core = { Namespace = "Rux", Version = "0.1.0" }
Text = { Namespace = "Rux", Version = "0.1.0" }
