[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Namespace = "Rux"
Name = "Math"
Version = "0.1.0"
Type = "Source"
Description = "Mathematical constants and functions"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
