// Module-level assembly text: sections, symbols and data definitions.

#include "CodeGen/X86_64/AssemblyModulePrinter.h"

#include "CodeGen/FloatLiteral.h"
#include "Ir/Lir/Lir.h"
#include "Target/Platform.h"

#include <cstring>
#include <format>

namespace Rux {
AssemblyModulePrinter::AssemblyModulePrinter(const Target::OS inputTargetOs)
    : targetOs(inputTargetOs) {
}

void AssemblyModulePrinter::EmitModuleData(const LirModule &module) {
    for (const auto &externalVariable : module.externVars) {
        DeclareExtern(externalVariable.name);
        data << "; extern var: " << externalVariable.name << '\n';
    }

    for (const auto &constant : module.consts) {
        if (constant.isPublic) {
            data << "global " << constant.name << '\n';
        }
        data << constant.name << ":  ; " << constant.type.ToString() << " = " << constant.value << '\n';
        data << "    ; (constant — initialized at link time)\n";
    }

    for (const auto &vtable : module.vtables) {
        rodata << vtable.label << ":\n";
        for (const auto &method : vtable.methods) {
            rodata << "    dq " << method << '\n';
        }
    }
}

bool AssemblyModulePrinter::DeclareFunction(const LirFunc &function) {
    if (function.isExtern) {
        DeclareExtern(function.name);
        return false;
    }
    if (function.isPublic) {
        DeclareGlobal(function.name);
    }
    return true;
}

void AssemblyModulePrinter::DeclareExtern(const std::string &name) {
    if (declaredExterns.insert(name).second) {
        externs << "extern " << name << '\n';
    }
}

void AssemblyModulePrinter::DeclareGlobal(const std::string &name) {
    globals << "global " << name << '\n';
}

std::string AssemblyModulePrinter::InternString(const std::string &value) {
    if (const auto existing = stringLabels.find(value); existing != stringLabels.end()) {
        return existing->second;
    }

    std::string label = std::format("__str{}", constantIndex++);
    stringLabels[value] = label;
    rodata << label << ":\n    db    ";
    for (const unsigned char character : value) {
        rodata << static_cast<int>(character) << ", ";
    }
    rodata << "0\n";
    return label;
}

std::string AssemblyModulePrinter::InternFloat32(const std::string &value) {
    if (const auto existing = float32Labels.find(value); existing != float32Labels.end()) {
        return existing->second;
    }

    std::string label = std::format("__f32_{}", constantIndex++);
    float32Labels[value] = label;
    std::uint32_t bits;
    if (value.starts_with("0x")) {
        bits = static_cast<std::uint32_t>(std::stoull(value, nullptr, 16));
    }
    else {
        const float parsed = ParseFloatLiteral<float>(value);
        std::memcpy(&bits, &parsed, sizeof(bits));
    }
    rodata << label << ":\n    dd    0x" << std::hex << bits << std::dec << '\n';
    return label;
}

std::string AssemblyModulePrinter::InternFloat64(const std::string &value) {
    if (const auto existing = float64Labels.find(value); existing != float64Labels.end()) {
        return existing->second;
    }

    std::string label = std::format("__f64_{}", constantIndex++);
    float64Labels[value] = label;
    std::uint64_t bits;
    if (value.starts_with("0x")) {
        bits = std::stoull(value, nullptr, 16);
    }
    else {
        const double parsed = ParseFloatLiteral<double>(value);
        std::memcpy(&bits, &parsed, sizeof(bits));
    }
    rodata << label << ":\n    dq    0x" << std::hex << bits << std::dec << '\n';
    return label;
}

std::string AssemblyModulePrinter::CreateLocalLabel(const std::string_view prefix) {
    return std::format("{}{}", prefix, constantIndex++);
}

void AssemblyModulePrinter::TextLine(const std::string_view line) {
    text << line << '\n';
}

void AssemblyModulePrinter::TextInstruction(const std::string_view instruction) {
    text << "    " << instruction << '\n';
}

void AssemblyModulePrinter::TextLabel(const std::string_view label) {
    text << label << ":\n";
}

void AssemblyModulePrinter::TextComment(const std::string_view comment) {
    text << "    ; " << comment << '\n';
}

void AssemblyModulePrinter::TextBlank() {
    text << '\n';
}

bool AssemblyModulePrinter::UsesWin64Convention() const {
    return PlatformDefaultConvention(targetOs, Target::Arch::X86_64) == CallingConvention::Win64;
}

std::string AssemblyModulePrinter::Finalize() {
    std::ostringstream output;
    output << "; Generated by Rux Compiler\n";
    if (UsesWin64Convention()) {
        output << "; Target:  x86-64  (Windows x64 ABI, NASM syntax)\n";
        output << "; Calling: rcx/rdx/r8/r9 (int args), xmm0-3 (float args)\n";
    }
    else {
        output << "; Target:  x86-64  (System V AMD64 ABI, NASM syntax)\n";
        output << "; Calling: rdi/rsi/rdx/rcx/r8/r9 (int args), xmm0-7 (float args)\n";
    }
    output << "; Scratch: r10, r11 (caller-saved)\n\n";
    output << "bits 64\n\n";
    if (const std::string declarations = externs.str(); !declarations.empty()) {
        output << declarations << '\n';
    }
    if (const std::string declarations = globals.str(); !declarations.empty()) {
        output << declarations << '\n';
    }
    if (const std::string section = rodata.str(); !section.empty()) {
        output << "section .rodata\n" << section << '\n';
    }
    if (const std::string section = data.str(); !section.empty()) {
        output << "section .data\n" << section << '\n';
    }
    if (const std::string section = text.str(); !section.empty()) {
        output << "section .text\n" << section;
    }
    return output.str();
}
} // namespace Rux
