[Manifest]
Version = 1
MinRux = "0.4.0"

[Workspace]
Packages = [
    "Packages/Algorithms",
    "Packages/Allocator",
    "Packages/C",
    "Packages/Collections",
    "Packages/Core",
    "Packages/Entropy",
    "Packages/Format",
    "Packages/FreeBSD",
    "Packages/Hash",
    "Packages/Io",
    "Packages/Json",
    "Packages/Linux",
    "Packages/macOS",
    "Packages/Math",
    "Packages/Memory",
    "Packages/Path",
    "Packages/Random",
    "Packages/Storage",
    "Packages/Text",
    "Packages/Time",
    "Packages/Unicode",
    "Packages/Uuid",
    "Packages/Windows",
]
