[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Namespace = "Rux"
Name = "Memory"
Version = "0.1.0"
Type = "SourceLibrary"
Description = "Memory management functions"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
Keywords = ["Memory", "Allocation", "Allocator", "Pointers"]
License = "MIT"
LicenseFile = "LICENSE.md"
Repository = "https://github.com/rux-lang/Rux"
Homepage = "https://rux-lang.dev/docs/api/memory"
ReadmeFile = "README.md"

[Dependencies]
Core = { Namespace = "Rux", Version = "0.1.0" }
FreeBSD = { Namespace = "Rux", Version = "0.1.0", TargetOS = ["FreeBSD"] }
Linux = { Namespace = "Rux", Version = "0.1.0", TargetOS = ["Linux"] }
MacOS = { Namespace = "Rux", Version = "0.1.0", TargetOS = ["MacOS"] }
Windows = { Namespace = "Rux", Version = "0.1.0", TargetOS = ["Windows"] }
