[Manifest]
Version = 1

[Package]
Namespace = "Rux"
Name = "Memory"
Version = "0.1.0"
Type = "Source"
Description = "Memory management functions"
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies]
Bsd = { Namespace = "Rux", Version = "*" }
Linux = { Namespace = "Rux", Version = "*" }
MacOS = { Namespace = "Rux", Version = "*" }
Rux = { Namespace = "Rux", Version = "*" }
Windows = { Namespace = "Rux", Version = "*" }
