[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Namespace = "Rux"
Name = "Json"
Version = "0.1.0"
Type = "SourceLibrary"
Description = "JSON parsing and serialization"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
Keywords = ["Json", "Serialization", "Parsing", "DataFormat", "Rfc8259"]
License = "MIT"
LicenseFile = "LICENSE.md"
Repository = "https://github.com/rux-lang/Rux"
Homepage = "https://rux-lang.dev/docs/api/json"
ReadmeFile = "README.md"

[Dependencies]
Allocator = { Namespace = "Rux", Version = "0.1.0" }
Collections = { Namespace = "Rux", Version = "0.1.0" }
Core = { Namespace = "Rux", Version = "0.1.0" }
Format = { Namespace = "Rux", Version = "0.1.0" }
Io = { Namespace = "Rux", Version = "0.1.0" }
Text = { Namespace = "Rux", Version = "0.1.0" }
