[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Namespace = "Rux"
Name = "Toml"
Version = "0.1.0"
Type = "SourceLibrary"
Description = "TOML parsing, serialization and streaming"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
Keywords = ["Toml", "Configuration", "Parsing", "DataFormat"]
License = "MIT"
LicenseFile = "LICENSE.md"
Repository = "https://github.com/rux-lang/Rux"
Homepage = "https://rux-lang.dev/docs/api/toml"
ReadmeFile = "README.md"

[Dependencies]
Allocator = { Namespace = "Rux", Version = "0.1.0" }
Collections = { Namespace = "Rux", Version = "0.1.0" }
Core = { Namespace = "Rux", Version = "0.1.0" }
Format = { Namespace = "Rux", Version = "0.1.0" }
Math = { Namespace = "Rux", Version = "0.1.0" }
Memory = { Namespace = "Rux", Version = "0.1.0" }
Text = { Namespace = "Rux", Version = "0.1.0" }
Time = { Namespace = "Rux", Version = "0.1.0" }
