name: FreeBSD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: FreeBSD x86-64

    steps:
      - uses: actions/checkout@v5

      - name: Build and test in FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            uname -a
            pkg install -y cmake llvm

          run: |
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
            cmake --build build
            echo 'import Std::Io::Print; func Main() -> int { Print("hello\n"); return 0; }' > /tmp/test.rux
            echo '[Package]' > /tmp/Rux.toml
            echo 'Name = "test"' >> /tmp/Rux.toml
            echo 'Type = "bin"' >> /tmp/Rux.toml
            echo '[Dependencies]' >> /tmp/Rux.toml
            echo 'Std = "*"' >> /tmp/Rux.toml
            mkdir -p /tmp/Src
            cp /tmp/test.rux /tmp/Src/Main.rux
            cd /tmp && ./build/rux build && ./build/rux run
            echo "---BASIC TEST DONE---"
            ./Tests/run_io_test.sh
            ./Tests/run_pow_test.sh
            ./Tests/run_unicode_test.sh
