name: Illumos

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: OmniOS x86-64

    steps:
      - uses: actions/checkout@v5

      - name: Build and test in OmniOS VM
        uses: vmactions/omnios-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            uname -a
            pkg install --accept developer/gcc14 ooce/developer/cmake

          run: |
            failed=0
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
            cmake --build build --parallel
            ctest --test-dir build -C Release --output-on-failure
