name: OpenBSD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: OpenBSD x86-64

    steps:
      - uses: actions/checkout@v5

      - name: Build and test in OpenBSD VM
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            uname -a
            pkg_add cmake

          run: |
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
            cmake --build build --parallel 4
            # Excluded within CMake, it won't actually run the tests, but it makes it
            # easier for when we can actually enable them
            ctest --test-dir build -C Release --output-on-failure